"""add_embedding_column_to_products

Revision ID: 5e1772cfdc3e
Revises: faab0ed8d130
Create Date: 2026-06-09 15:39:56.771089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "5e1772cfdc3e"
down_revision: Union[str, Sequence[str], None] = "faab0ed8d130"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("embedding", Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "embedding")
    # ### end Alembic commands ###
